### ISSUE TITLE
install.sh breaks if executed from within gnome terminal

### ISSUE THREAD

**Issue by misterhayman** [labjack/exodriver#22]
The install script breaks when executed from within gnome terminal because of a call to "logname" which was broken by a recent change detailed here:
https://bugzilla.gnome.org/show_bug.cgi?id=747046#c10

The install script works fine if executed from within xterm.

It might make sense to revert f9f89f1e7fa73a6a195484a7cfb7e4acae76f736 ?

**Comment by rolsen** [comment]
Thank you for bringing this to our attention—a fix is on the way.

Instead of reverting, we're testing getting rid of the `logname`/`$USER` stuff. Instead, we're thinking of moving 10-labjack.rules to 90-labjack.rules and adding a MODE="0666", so that all users can use LabJack devices without being in the `adm` group (so there's no need to get the real user name).

**Comment by rolsen** [comment]
Fixed in 016cb13d06cb410a8b51acc68dcde8258df18a94.
