### ISSUE TITLE
Question about LJUSB_OpenAllDevicesOfProductId  warning

### ISSUE THREAD

**Issue by ferchaure** [labjack/exodriver#38]
Hi,
I'm using exodrive from Matlab and got a warning when I load labjackusb and labjackusb.h  : 
`Warning: The data type 'voidPtrPtrPtr' used by function LJUSB_OpenAllDevicesOfProductId does not exist. `

Everything else works perfect (I'm not using that function really), but I think maybe is useful that I report this.

Best,
Fernando Chaure

**Comment by sjarman28** [comment]
This is a problem with MATLAB's ability to handle pointers and there is not really anything we can do with the Exodriver to fix it. I would recommend you do not try to use this function in MATLAB.

If you are interested in the details, the problem is that `LJUSB_OpenAllDevicesOfProductId` has an input parameter with the type `HANDLE **`. That is a pointer to a pointer of a `HANDLE`. It is somewhat implied that this is a pointer to a `HANDLE` array. `HANDLE` is defined as `void *`, so in literal terms the input parameter is a pointer to a pointer of a void pointer... very tedious stuff. It is not a surprise MATLAB complains about it, but it is really just passing along an array of connection handles and works fine in the native C language. There may have been a better way to implement the function to make it easier to use in other programming languages, but at this point it does not make sense to break the backwards compatibility of the library to change it.
